// Generated by boost/cellnet/protoc-gen-msg
// DO NOT EDIT!
// Source: gamedef.proto

package gamedef

import (
	"boost/cellnet"
	"reflect"
	_ "boost/cellnet/codec/pb"
)

func init() {

	// gamedef.proto
	cellnet.RegisterMessageMeta("pb", "gamedef.TestEchoACK", reflect.TypeOf((*TestEchoACK)(nil)).Elem(), 1899977859)

}
