language: go

install:
  - go get -v boost/golog
  - go get -v boost/goobjfmt
  - go get -v boost/gosproto
  - go get -v github.com/golang/protobuf/proto
  - go get -v github.com/gorilla/websocket

go:
  - 1.8

script:
  - go test -v boost/cellnet/tests

after_success:
  - bash <(curl -s https://codecov.io/bash)